package ru.geekbrains.chat_common;

public enum MessageType {
    PUBLIC,
    PRIVATE,
    AUTH_REQUEST,
    AUTH_SUCCESS,
    AUTH_FAILURE,
    CREATE_USER_REQUEST,
    CREATE_USER_SUCCESS,
    CREATE_USER_FAILURE,
    CREATE_USER_USERNAME_EXISTS,
    CREATE_USER_LOGIN_EXISTS,
    CHANGE_PASSWORD_REQUEST,
    CHANGE_PASSWORD_SUCCESS,
    CHANGE_PASSWORD_FAILURE,
    CHANGE_PASSWORD_LOGIN_FAILURE,
    CHANGE_PASSWORD_LOGIN_CHECK,
    CHANGE_PASSWORD_LOGIN_EXISTS,
    CHANGE_USERNAME_REQUEST,
    CHANGE_USERNAME_SUCCESS,
    CHANGE_USERNAME_FAILURE,
    CHANGE_USERNAME_INCORRECT_PASSWORD,
    ONLINE_USERS_LIST,
    SUBSCRIBE_REQUEST
}
