package ru.geekbrains.chat_common;

public enum MessageType {
    PUBLIC,
    PRIVATE,
    AUTH_REQUEST,
    AUTH_SUCCESS,
    AUTH_FAILURE,
    CREATE_USER_REQUEST,
    CREATE_USER_SUCCESS,
    CREATE_USER_FAILURE,
    CHANGE_USERNAME_REQUEST,
    CHANGE_USERNAME_SUCCESS,
    CHANGE_USERNAME_FAILURE,
    CHANGE_PASSWORD_REQUEST,
    CHANGE_PASSWORD_SUCCESS,
    CHANGE_PASSWORD_FAILURE,
    ONLINE_USERS_LIST,
    SUBSCRIBE_REQUEST
}
